#!/usr/bin/env bash
# Ce script ping une adresse IP 5 fois

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
# Envoyez un ping à l'adresse IP 5 fois
ping -c 5 "$1"