#!/usr/bin/env bash
# Ce script modifie le fichier /etc/hosts pour modifier les adresses IP de localhost et facebook.com

# Sauvegarde du fichier hosts d'origine
cp /etc/hosts /etc/hosts.bak

# Supprimer d'éventuelles anciennes entrées
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

# Ajouter la nouvelle entrée pour localhost
echo "127.0.0.2 localhost" >> /etc/hosts

# Ajouter la redirection de facebook.com
echo "8.8.8.8 facebook.com" >> /etc/hosts
