#!/usr/bin/env bash
# Ce script affiche toutes les adresses IPv4 actives sur la machine

# Obtenir la configuration réseau
ifconfig | \
  # Filtrer les lignes contenant les adresses IP
  grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | \
  # Extraire uniquement les adresses IP
  grep -Eo '([0-9]*\.){3}[0-9]*'
